POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHRpIiwiaWQiOiI1YThhZjQ0MTJmNjViNDE0MzA4ZmY2N2MiLCJpYXQiOjE1MTkwNTYxMDF9.LCgvzxxSPVr6_3sRWPyixJNryoI7ni5MfMem3H2og2E

{
  "title": "Coding coders code cody code",
  "author": "Jaakko",
  "url": "www.blogi.fi",
  "likes": 0
}